eagames/urls.py
from registration.forms import RegistrationFormUniqueEmail
from registration.views import RegistrationView
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles import views
from django.contrib.auth.views import login, logout
from django.conf import settings
#from rpc import api_router
from accounts.forms import CustomRegistrationForm, CustomRegistrationFormUniqueEmail
from accounts.views import SettingsView, PaymentSettingsView, SecuritySettingsView, RatesView, HistoryExpressView, \
    ReferalView
from core.views import HomePageView, LineBetsView, DetailBetsView, sert, ExpressView, TestView
from eagames.rpc import api_router
from payment.views import PaymentView, CashoutView, payment

admin.autodiscover()



urlpatterns = patterns('',

    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^1EDEF48E2BFBCD73E1C4E6C164816E3D.txt', sert, name='sert'),
    url(r'^4007d082e58e.html', TestView.as_view(), name='html'),
    url(r'^table/$', LineBetsView.as_view(), name='linetable'),
    url(r'^table/many/$', 'core.views.linetable_many', name='linetable-many'),
    url(r'^express/$', ExpressView.as_view(), name='express'),
    url(r'^table/(?P<slug>[-\w]+)/$', DetailBetsView.as_view(), name='detailline'),

    url(r'^rates/$', RatesView.as_view(), name='rates'),
    url(r'^express/history$', HistoryExpressView.as_view(), name='express-history'),

    url(r'^referal/$', ReferalView.as_view(), name='referal'),

    url(r'^test', 'chat.views.test', name='test'),
    url(r'^apichat/upload$', 'chat.views.upload', name='upload'),
    url(r'^apichat/api/', include(api_router.urls)),
    
    #payment
    url(r'^payment/$', PaymentView.as_view(), name='payment-pay'),
    url(r'^payment/get$', payment, name='payment-get'),
    url(r'^cashout/$', CashoutView.as_view(), name='cashout'),

    # accounts - base actions
    (r'^accounts/login/$',  login),
    (r'^accounts/logout/$', logout, {'next_page': '/'}),

    #accounts pages
    url(r'^accounts/settings/$', SettingsView.as_view(), name='settings'),
    url(r'^accounts/settings/payment/$', PaymentSettingsView.as_view(), name='payment-settings'),
    url(r'^accounts/settings/security/$', SecuritySettingsView.as_view(), name='security-settings'),

    # accounts - integrate with third apps
    url(r'^accounts/register/$', 'accounts.views.registration',
            name='registration'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^social/', include('social_auth.urls')),

    (r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
       'document_root': settings.MEDIA_ROOT}),

    # articles
    url('', include('arcticles.urls')),


)
"""
    url(r'^accounts/register/$', 'accounts.views.registration',
            name='registration'),
    url(r'^accounts/password/change/$', auth_views.password_change,
            name='password_change'),
    url(r'^accounts/password/change/done/$', auth_views.password_change_done,
            name='password_change_done'),
    url(r'^accounts/password/reset/$', auth_views.password_reset,
            {'password_reset_form': MyPasswordResetForm}, name='password_reset'),
    url(r'^accounts/password/reset/done/$',
            auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/password/reset/complete/$',
            auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.password_reset_confirm, name='password_reset_confirm'),
"""


urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
]

app/payment/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from datetime import datetime
from accounts import UserProfile


class PaymentSum(models.Model):
    sum = models.PositiveIntegerField(default=1)
    gift = models.PositiveIntegerField(default=1)

class BidPayment(models.Model):
    TYPE_WHO = 0
    TYPE_REP = 1
    TYPE_LIST = 2

    TYPE_CHOICES = (
        (TYPE_WHO, 'Ожидает'),
        (TYPE_REP, 'В процессе'),
        (TYPE_LIST, 'Выплачено'),
    )
    TYPE_ONE = 0
    TYPE_TWO = 1

    TYPE_SYSTEM = (
        (TYPE_ONE, 'WebMoney'),
        (TYPE_TWO, 'QIWI'),
    )
    user = models.ForeignKey(UserProfile, related_name='user_bid')
    result = models.IntegerField(choices=TYPE_CHOICES, blank=True, null=True, default=0)
    system = models.IntegerField(choices=TYPE_SYSTEM, blank=True, null=True, default=0)
    sum = models.PositiveIntegerField(default=0)
    number = models.CharField(_('Номер кошелька'), max_length=15, blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Order(models.Model):
    user = models.ForeignKey(UserProfile,related_name='order-user')
    sum = models.PositiveIntegerField(default=0, blank=True, null=True)
    good = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

app/payment/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from payment.models import BidPayment


class PaymentForm(ModelForm):
    class Meta:
        model = BidPayment

    fields = '__all__'

app/payment/views.py
# -*- coding: utf-8 -*-
import json
import datetime
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
import hashlib
# Create your views here.
from django.template import RequestContext
from django.template.loader import render_to_string
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib import messages
from payment.forms import PaymentForm
from payment.models import *


class PaymentView(TemplateView):
    template_name = 'payment/pay.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context['payments'] = PaymentSum.objects.all()
        return context

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated():
                return redirect('auth_login')
        return super(PaymentView, self).dispatch(*args, **kwargs)

class CashoutView(TemplateView):
    template_name = 'payment/cashout.html'

    def get_context_data(self, **kwargs):
        context = super(CashoutView, self).get_context_data(**kwargs)
        context['form'] = PaymentForm()
        context['bids'] = BidPayment.objects.all().order_by('-created')
        return context

    def post(self, request, *args, **kwargs ):
        context = RequestContext(request)
        data = {}
        print(request.POST)
        if request.POST['summa'] == '':
            data['error'] = "Введите сумму!"
            response = HttpResponse(json.dumps({'data':data}), content_type="application/json")
            return response
        elif request.POST['number'] == '':
            data['error'] = "Введите номер телефона!"
            response = HttpResponse(json.dumps({'data':data}), content_type="application/json")
            return response
        if int(request.POST['summa']) > int(request.user.amount):
            data['error'] = "Сумма на вывод первышает допустимую!"
            response = HttpResponse(json.dumps({'data':data}), content_type="application/json")
            return response
        else:
            bid = BidPayment.objects.create(user=request.user, system=int(request.POST['sistema']),
                                            sum=int(request.POST['summa']), number=int(request.POST['number']))
            data['success'] = "Заявка успешно создана!"

        response = HttpResponse(json.dumps({'data':data}), content_type="application/json")
        return response

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated():
                return redirect('auth_login')
        return super(CashoutView, self).dispatch(*args, **kwargs)

def payment(request):
    merchant_id = settings.ID_MAGAZINE
    secret_key = settings.ID_SECRET_KEY
    if 'sum' in request.GET:
        out_amount = request.GET['sum']
        order = Order.objects.create(user=request.user, sum=out_amount)
        str_h = merchant_id + ':' + str(out_amount) + ':' + secret_key + ':' + str(order.id)
        hsh = hashlib.md5()
        hsh.update(str_h)
        signature = hsh.hexdigest()
        url = 'http://www.free-kassa.ru/merchant/cash.php?m=' + merchant_id + '&oa=' + \
              str(out_amount) + '&s=' + str(signature) + '&o=' + str(order.id)
        return HttpResponseRedirect(url)
    elif 'summa' in request.GET:
        out_amount = request.GET['summa']
        order = Order.objects.create(user=request.user, sum=out_amount)
        str_h = merchant_id + ':' + str(out_amount) + ':' + secret_key + ':' + str(order.id)
        hsh = hashlib.md5()
        hsh.update(str_h)
        signature = hsh.hexdigest()
        url = 'http://www.free-kassa.ru/merchant/cash.php?m=' + merchant_id + '&oa=' + \
              str(out_amount) + '&s=' + str(signature) + '&o=' + str(order.id)
        return HttpResponseRedirect(url)

templates/payment/cashout.html
{% extends 'core/base.html' %}

{% block title %}Вывести средства{% endblock %}



{% block content %}

    <div class="blog-main">

        <div class="tabs-settings">
               <div class="tabs-header-settings"></div>
               {% with u=request.resolver_match.url_name %}
               <input id="tab_1-settings" class="input-tabs-settings" type="radio" name="tab-settings" {% if u == 'payment-pay' %}checked="checked"{% endif %} />
	           <input id="tab_2-settings" class="input-tabs-settings" type="radio" name="tab-settings" {% if u == 'cashout' %}checked="checked"{% endif %} />
               <label onclick="javascript:document.location.href='{% url 'payment-pay' %}'" for="tab_1-settings" class="label-tabs-settings" id="tab_l1-settings">Пополнить счет</label>
	           <label onclick="javascript:document.location.href='{% url 'cashout' %}'" for="tab_2-settings" class="label-tabs-settings" id="tab_l2-settings">Вывести средств</label>
               {% endwith %}
               <div style="clear:both"></div>
               <div class="tabs_cont-settings">
               <div  class="pay-settings" id="tab_c1-settings"></div>

               <div id="tab_c2-settings">
                   <div class="form-cashout">
                        <form data-submit="FormCashoutCallback"  role="form" class="bets-form form-horizontal form-v2 ajaxify-form" action='{% url 'cashout' %}' method='post'>
                     <div style="display:none"><input type="hidden" id="csrfmiddlewaretoken" name="csrfmiddlewaretoken" value=""></div>
                     <div class="form-group">
                         <h4>Выберете платежную систему</h4>
                         <select class="form-control" name="sistema">
                           <option value="0">WebMoney</option>
                           <option value="1">QIWI</option>
                          </select>
                     </div>
                     <div class="form-group">
                            <h4>Введите  номер телефона</h4>
                            <input placeholder="Введите номер телефона"  class="form-control" type="number" name="number" value="" id="summa">
                     </div>
                     <div class="form-group">
                           <h4>Введите сумму</h4>
                           <input placeholder="Введите сумму" class="form-control" type="number" name="summa" value="" id="summa">
                     </div>
                     <button class="btn btn-lg btn-primary btn-block submit-trigger" type="submit">Вывести</button>
                         </form>
                   </div><br>

                   <br>
               {% if  bids %}
                   <table class="table table-striped table-res">
              <thead>
                <tr>
                    <th>Дата заказа</th>
                    <th>Система</th>
                    <th>Кошелек</th>
                    <th>Сумма</th>
                    <th>Статус</th>
                </tr>
              </thead>
              <tbody>
              {% for bid in bids %}
                <tr>
                  <td>{{ bid.created|date:"j/n/Y H:i:s" }}</td>
                  <td>{{ bid.get_system_display }}</td>
                  <td>{{ bid.number }}</td>
                  <td>{{ bid.sum }}</td>
                  <td>{{ bid.get_result_display }}</td>
                </tr>

              {% endfor %}
              </tbody>
            </table>
                {% endif %}

               </div>



               </div>

           </div>

    </div>


{% endblock %}

templates/payment/pay.html
{% extends 'core/base.html' %}

{% block title %}Положить{% endblock %}



{% block content %}

    <div class="blog-main">

        <div class="tabs-settings">
               <div class="tabs-header-settings"></div>
               {% with u=request.resolver_match.url_name %}
               <input id="tab_1-settings" class="input-tabs-settings" type="radio" name="tab-settings" {% if u == 'payment-pay' %}checked="checked"{% endif %} />
	           <input id="tab_2-settings" class="input-tabs-settings" type="radio" name="tab-settings" {% if u == 'cashout' %}checked="checked"{% endif %} />
               <label onclick="javascript:document.location.href='{% url 'payment-pay' %}'" for="tab_1-settings" class="label-tabs-settings" id="tab_l1-settings">Пополнить счет</label>
	           <label onclick="javascript:document.location.href='{% url 'cashout' %}'" for="tab_2-settings" class="label-tabs-settings" id="tab_l2-settings">Вывести средств</label>
               {% endwith %}

               <div style="clear:both"></div>

               <div class="tabs_cont-settings">
               <div  class="pay-settings" id="tab_c1-settings">
                   {% if payments %}
                       <h2>Воспользуйтесь пакетом</h2>
                   {% endif %}
                   {% for pay in payments %}
                          <a class="link-pay-get" href="{% url 'payment-get' %}?sum={{ pay.sum }}&gift={{ pay.gift }}">
                              <div class="div-pay-get">Пополнить счет на {{ pay.sum }}р</div>
                              <div class="gift-pay-get">+ {{ pay.gift }}р в подарок</div>
                          </a>


                   {% endfor %}
                   <h2>Или укажите сумму сами</h2>
                   <form class="form-pay" action='{% url 'payment-get' %}' method='get'>
                     <div style="display:none"><input type="hidden" id="csrfmiddlewaretoken" name="csrfmiddlewaretoken" value=""></div>
                     <input placeholder="Введите сумму" type="summa" name="summa" value="" id="summa">
                     <input class="pay-button" type="submit" value="Далее" />
                   </form>
               </div>

               <div id="tab_c2-settings">
               </div>



               </div>

           </div>

    </div>


{% endblock %}